import type { Metadata } from "next";
import "./globals.css";
import SideNav from './ui/sidenav';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white flex justify-center gap-6">
        <div className="w-2/12">
          <SideNav/>
        </div>
        <div className="w-6/12">
          {children}
        </div>
      </body>
    </html>
  );
}
